jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Siriru\AntBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Siriru\AntBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        root:
            pattern: ^/$
            security: false

        home:
            pattern: ^/home$
            security: false

        login:
            pattern:  ^/login$
            security: false

        register:
            pattern: ^/account/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                username_parameter: username
                password_parameter: password

            logout:
                path:   /logout
                target: /home

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
